//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DAO.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marque.
        /// </summary>
        public static string ArticleBrand {
            get {
                return ResourceManager.GetString("ArticleBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détails / Couleur.
        /// </summary>
        public static string ArticleDetails {
            get {
                return ResourceManager.GetString("ArticleDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jouet.
        /// </summary>
        public static string ArticleisToy {
            get {
                return ResourceManager.GetString("ArticleisToy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        public static string ArticleName {
            get {
                return ResourceManager.GetString("ArticleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prix.
        /// </summary>
        public static string ArticlePrice {
            get {
                return ResourceManager.GetString("ArticlePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taille.
        /// </summary>
        public static string ArticleSize {
            get {
                return ResourceManager.GetString("ArticleSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ville.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courriel.
        /// </summary>
        public static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vêtements.
        /// </summary>
        public static string NumberClothes {
            get {
                return ResourceManager.GetString("NumberClothes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jouets.
        /// </summary>
        public static string NumberToys {
            get {
                return ResourceManager.GetString("NumberToys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Téléphone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
    }
}
